SELECT  BW_CELL.ID   CELL_ID, 
	BW_CELL.CELL_TYPE,
	BW_STRING_VALUE.STRING_VALUE   CELL_STRING_VALUE, 	
	'-1' CELL_INTEGER_VALUE,
	'1.1' CELL_DOUBLE_VALUE,
	'-1' CELL_TBL_VALUE,
	BW_STRING_VALUE.TX_ID,
	BW_TXS.DESCRIPTION,
	BW_TXS.COMMENT_,
	BW_USER.EMAIL_ADDRESS,
	BW_TXS.CREATED_ON,
	BW_CELL.BW_ROW_ID,
	BW_CELL.BW_COLUMN_ID
FROM 
	(
	SELECT BW_STRING_VALUE.BW_CELL_ID, MAX ( BW_STRING_VALUE.ID )    MAX_VALUE_ID
	FROM BW_CELL, BW_STRING_VALUE, BW_COLUMN, BW_TXS
	WHERE 
		 BW_CELL.BW_COLUMN_ID = BW_COLUMN.ID
	      AND BW_COLUMN.ID = ?
	      AND BW_CELL.ID = BW_STRING_VALUE.BW_CELL_ID
	      AND BW_STRING_VALUE.TX_ID = BW_TXS.TX_ID
	      AND BW_TXS.CREATED_ON < ?
	GROUP BY BW_STRING_VALUE.BW_CELL_ID 
	)
	  MAXVALUETBL,
	BW_CELL, BW_COLUMN, BW_STRING_VALUE,BW_TXS,BW_USER,BW_ROW
WHERE 	BW_CELL.BW_COLUMN_ID = BW_COLUMN.ID
	AND BW_COLUMN.ID = ?
	AND BW_CELL.ID = BW_STRING_VALUE.BW_CELL_ID
	AND BW_CELL.ID = MAXVALUETBL.BW_CELL_ID      
	AND BW_STRING_VALUE.ID = MAXVALUETBL.MAX_VALUE_ID
	AND BW_CELL.CELL_TYPE='STRING'
	AND  BW_STRING_VALUE.TX_ID = 	BW_TXS.TX_ID
	AND BW_USER.ID = BW_TXS.CREATED_BY
	AND BW_ROW.ID = BW_CELL.BW_ROW_ID
	AND BW_ROW.IS_ACTIVE = 1