SELECT 	
	BW_COLLAB.ID  COLLAB_ID,
	BW_COLLAB.NAME  COLLAB_NAME,
	BW_COLLAB.PURPOSE  COLLAB_PURPOSE,
	BW_WB.ID  WB_ID,
	BW_WB.NAME  WB_NAME,
	BW_TBL.NAME  TABLE_NAME,
	BW_TBL.PURPOSE  TABLE_PURPOSE,
	BW_NH_ACCESS.ID  ACCESS_ID, 			
	BW_NH_ACCESS.REL, 
	BW_NH_ACCESS.TABLE_ID,
	BW_NH_ACCESS.OBJECT_TYPE,
	BW_NH_ACCESS.OBJECT_ID,
	BW_NH_ACCESS.ACCESS
FROM  
	BW_MEMBER, 
	BW_TBL,
	BW_NH_ACCESS,
	BW_NH_REL,
	BW_WB,
	BW_COLLAB,
	BW_BL_TBL  BASELINE_TBL
WHERE 
	BW_MEMBER.ID = ?
	AND BW_NH_REL.REL = BW_NH_ACCESS.REL
	AND BW_NH_REL.TARGET_NH_ID = BW_MEMBER.NEIGHBORHOOD_ID
	AND BW_NH_REL.NEIGHBORHOOD_ID = BW_TBL.NEIGHBORHOOD_ID
	AND  BW_NH_ACCESS.TABLE_ID = BW_TBL.ID
	AND 	BW_TBL.BW_WB_ID =BW_WB.ID 
	AND BW_WB.ID = ?
	AND  BW_COLLAB.ID =  BW_WB.BW_COLLAB_ID
	AND   BW_NH_ACCESS.ACCESS > 0
	AND BASELINE_TBL.TABLE_ID = BW_TBL.ID
	AND BASELINE_TBL.BASELINE_ID = ?

UNION ALL

SELECT 	
	BW_COLLAB.ID  COLLAB_ID,
	BW_COLLAB.NAME  COLLAB_NAME,
	BW_COLLAB.PURPOSE  COLLAB_PURPOSE,
	BW_WB.ID  WB_ID,
	BW_WB.NAME  WB_NAME,
	BW_TBL.NAME  TABLE_NAME,
	BW_TBL.PURPOSE  TABLE_PURPOSE,
	BW_NH_ACCESS.ID  ACCESS_ID, 			
	BW_NH_ACCESS.REL, 
	BW_NH_ACCESS.TABLE_ID,
	BW_NH_ACCESS.OBJECT_TYPE,
	BW_NH_ACCESS.OBJECT_ID,
	BW_NH_ACCESS.ACCESS
FROM  
	BW_MEMBER, 
	BW_TBL,
	BW_NH_ACCESS,
	BW_USER,
	BW_TXS,
	BW_WB,
	BW_COLLAB,
	BW_BL_TBL  BASELINE_TBL
WHERE 
	BW_TBL.NEIGHBORHOOD_ID =  BW_MEMBER.NEIGHBORHOOD_ID
	AND BW_MEMBER.ID = ?
	AND BW_USER.ID = BW_MEMBER.USER_ID
	AND  BW_TXS.TX_ID = BW_TBL.TX_ID
	AND  BW_TXS.CREATED_BY =  BW_USER.ID
	AND  BW_NH_ACCESS.REL = 'CREATOR'
	AND  BW_NH_ACCESS.TABLE_ID = BW_TBL.ID
	AND   BW_NH_ACCESS.ACCESS > 0
	AND 	BW_TBL.BW_WB_ID =BW_WB.ID 
	AND BW_WB.ID = ?
	AND  BW_COLLAB.ID =  BW_WB.BW_COLLAB_ID
	AND BASELINE_TBL.TABLE_ID = BW_TBL.ID
	AND BASELINE_TBL.BASELINE_ID = ?
UNION ALL
SELECT 	
	BW_COLLAB.ID  COLLAB_ID,
	BW_COLLAB.NAME  COLLAB_NAME,
	BW_COLLAB.PURPOSE  COLLAB_PURPOSE,
	BW_WB.ID  WB_ID,
	BW_WB.NAME  WB_NAME,
	BW_TBL.NAME  TABLE_NAME,
	BW_TBL.PURPOSE  TABLE_PURPOSE,
	BW_NH_ACCESS.ID  ACCESS_ID, 			
	BW_NH_ACCESS.REL, 
	BW_NH_ACCESS.TABLE_ID,
	BW_NH_ACCESS.OBJECT_TYPE,
	BW_NH_ACCESS.OBJECT_ID,
	BW_NH_ACCESS.ACCESS
FROM  
	BW_MEMBER, 
	BW_TBL,
	BW_NH_ACCESS,
	BW_NH  MEMBER_NH,
	BW_NH  TABLE_NH,
	BW_WB,
	BW_COLLAB,
	BW_BL_TBL  BASELINE_TBL
WHERE 
	     	
	BW_MEMBER.ID = ?
	AND MEMBER_NH.ID =   BW_MEMBER.NEIGHBORHOOD_ID
	AND TABLE_NH.ID = BW_TBL.NEIGHBORHOOD_ID
	AND TABLE_NH.LEVEL_0_ID = 	MEMBER_NH.LEVEL_0_ID
	AND  BW_NH_ACCESS.TABLE_ID = BW_TBL.ID
	AND BW_NH_ACCESS.REL = 'DOMAIN'   
	AND 	BW_TBL.BW_WB_ID = BW_WB.ID
	AND BW_WB.ID = ?
	AND  BW_COLLAB.ID =  BW_WB.BW_COLLAB_ID
	AND   BW_NH_ACCESS.ACCESS > 0    
	AND BASELINE_TBL.TABLE_ID = BW_TBL.ID
	AND BASELINE_TBL.BASELINE_ID = ?    
UNION ALL
	
SELECT
	BW_COLLAB.ID  COLLAB_ID,
	BW_COLLAB.NAME  COLLAB_NAME,
	BW_COLLAB.PURPOSE  COLLAB_PURPOSE,
	BW_WB.ID  WB_ID,
	BW_WB.NAME  WB_NAME,
	BW_TBL.NAME  TABLE_NAME,
	BW_TBL.PURPOSE  TABLE_PURPOSE,
	BW_NH_ACCESS.ID  ACCESS_ID, 			
	BW_NH_ACCESS.REL, 
	BW_NH_ACCESS.TABLE_ID,
	BW_NH_ACCESS.OBJECT_TYPE,
	BW_NH_ACCESS.OBJECT_ID,
	BW_NH_ACCESS.ACCESS
	
FROM  
	BW_NH_ACCESS,
	BW_TBL,
	BW_WB,
	BW_COLLAB,
	BW_BL_TBL  BASELINE_TBL
WHERE 
	BW_NH_ACCESS.REL = 'PUBLIC'
	AND  BW_NH_ACCESS.TABLE_ID = BW_TBL.ID
	AND   BW_NH_ACCESS.ACCESS > 0
	AND 	BW_TBL.BW_WB_ID =BW_WB.ID 
	AND BW_WB.ID = ?
	AND  BW_COLLAB.ID =  BW_WB.BW_COLLAB_ID
	AND BASELINE_TBL.TABLE_ID = BW_TBL.ID
	AND BASELINE_TBL.BASELINE_ID = ?

ORDER BY  COLLAB_NAME, WB_NAME, TABLE_NAME


GO
