SELECT 	
		BW_NH_ACCESS.ID, 			
		BW_NH_ACCESS.REL, 
		BW_NH_ACCESS.TABLE_ID,
		BW_NH_ACCESS.OBJECT_TYPE,
		BW_NH_ACCESS.OBJECT_ID,
		BW_NH_ACCESS.ACCESS_
FROM  
     BW_NH_ACCESS
WHERE 
     BW_NH_ACCESS.TABLE_ID = ?
   AND  OBJECT_TYPE = 'TABLE'