SELECT 	
		BW_NH_ACCESS.ID, 			
		BW_NH_ACCESS.REL, 
		BW_NH_ACCESS.TABLE_ID,
		BW_NH_ACCESS.OBJECT_TYPE   NHA_OBJECT_TYPE,
		BW_NH_ACCESS.OBJECT_ID   NHA_OBJECT_ID,
		BW_NH_ACCESS.ACCESS_
FROM  
     BW_MEMBER, 
     BW_TBL,
     BW_NH_ACCESS,
     BW_NH_REL
WHERE 
     BW_MEMBER.ID = ?
     AND BW_NH_REL.REL = BW_NH_ACCESS.REL
     AND BW_NH_REL.TARGET_NH_ID = BW_MEMBER.NEIGHBORHOOD_ID
     AND BW_NH_REL.NEIGHBORHOOD_ID = BW_TBL.NEIGHBORHOOD_ID
     AND BW_NH_ACCESS.TABLE_ID = BW_TBL.ID
     AND BW_TBL.ID = ?
   
UNION
SELECT 	BW_NH_ACCESS.ID, 		
		BW_NH_ACCESS.REL, 
		BW_NH_ACCESS.TABLE_ID,
		BW_NH_ACCESS.OBJECT_TYPE   NHA_OBJECT_TYPE,
		BW_NH_ACCESS.OBJECT_ID   NHA_OBJECT_ID,
		BW_NH_ACCESS.ACCESS_
FROM  
		     BW_MEMBER, 
		     BW_TBL,
		     BW_NH_ACCESS,
		     BW_USER,
		     BW_TXS
WHERE 
	     	BW_TBL.NEIGHBORHOOD_ID =  BW_MEMBER.NEIGHBORHOOD_ID
	    AND BW_MEMBER.ID = ?
	    AND BW_USER.ID = BW_MEMBER.USER_ID
	   AND  BW_TXS.TX_ID = BW_TBL.TX_ID
	    AND  BW_TXS.CREATED_BY =  BW_USER.ID
	    AND  BW_NH_ACCESS.REL = 'CREATOR'
	    AND  BW_NH_ACCESS.TABLE_ID = BW_TBL.ID
	    AND 	BW_TBL.ID = ?
UNION
SELECT 	BW_NH_ACCESS.ID, 		
		BW_NH_ACCESS.REL, 
		BW_NH_ACCESS.TABLE_ID,
		BW_NH_ACCESS.OBJECT_TYPE   NHA_OBJECT_TYPE,
		BW_NH_ACCESS.OBJECT_ID   NHA_OBJECT_ID,
		BW_NH_ACCESS.ACCESS_
FROM  
		     BW_MEMBER, 
		     BW_TBL,
		     BW_NH_ACCESS,
		     BW_NH   MEMBER_NH,
		      BW_NH   TABLE_NH
WHERE 
	     	
	     BW_MEMBER.ID = ?
	    AND MEMBER_NH.ID =   BW_MEMBER.NEIGHBORHOOD_ID
	    AND TABLE_NH.ID = BW_TBL.NEIGHBORHOOD_ID
	    AND TABLE_NH.LEVEL_0_ID = 	MEMBER_NH.LEVEL_0_ID
	    AND  BW_NH_ACCESS.TABLE_ID = BW_TBL.ID
	    AND 	BW_TBL.ID = ?
	    AND BW_NH_ACCESS.REL = 'DOMAIN'
UNION
	
SELECT BW_NH_ACCESS.ID, 		
	BW_NH_ACCESS.REL, 
	BW_NH_ACCESS.TABLE_ID,
	BW_NH_ACCESS.OBJECT_TYPE   NHA_OBJECT_TYPE,
	BW_NH_ACCESS.OBJECT_ID   NHA_OBJECT_ID,
	BW_NH_ACCESS.ACCESS_
FROM  
     BW_NH_ACCESS
WHERE 
       BW_NH_ACCESS.REL = 'PUBLIC'
     AND  BW_NH_ACCESS.TABLE_ID = ?
 ORDER BY  NHA_OBJECT_TYPE, NHA_OBJECT_ID
