/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.2
 * Contact: apisupport@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.model.CellStatus;
import io.swagger.model.StringValues;
import io.swagger.model.Transaction;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;

/**
 * CellChain
 */

public class CellChain   {
  @JsonProperty("gridId")
  private Integer gridId = null;

  @JsonProperty("cellId")
  private Integer cellId = null;

  @JsonProperty("rowId")
  private Integer rowId = null;

  @JsonProperty("columnId")
  private Integer columnId = null;

  @JsonProperty("cellType")
  private String cellType = null;

  @JsonProperty("isActive")
  private Boolean isActive = null;

  @JsonProperty("lastTxDetails")
  private List<Transaction> lastTxDetails = null;

  @JsonProperty("cellHistory")
  private List<StringValues> cellHistory = null;

  @JsonProperty("cellStatus")
  private List<CellStatus> cellStatus = null;

  public CellChain gridId(Integer gridId) {
    this.gridId = gridId;
    return this;
  }

  /**
   * Get gridId
   * @return gridId
   **/
  @JsonProperty("gridId")
  @ApiModelProperty(value = "")
  public Integer getGridId() {
    return gridId;
  }

  public void setGridId(Integer gridId) {
    this.gridId = gridId;
  }

  public CellChain cellId(Integer cellId) {
    this.cellId = cellId;
    return this;
  }

  /**
   * Get cellId
   * @return cellId
   **/
  @JsonProperty("cellId")
  @ApiModelProperty(value = "")
  public Integer getCellId() {
    return cellId;
  }

  public void setCellId(Integer cellId) {
    this.cellId = cellId;
  }

  public CellChain rowId(Integer rowId) {
    this.rowId = rowId;
    return this;
  }

  /**
   * Get rowId
   * @return rowId
   **/
  @JsonProperty("rowId")
  @ApiModelProperty(value = "")
  public Integer getRowId() {
    return rowId;
  }

  public void setRowId(Integer rowId) {
    this.rowId = rowId;
  }

  public CellChain columnId(Integer columnId) {
    this.columnId = columnId;
    return this;
  }

  /**
   * Get columnId
   * @return columnId
   **/
  @JsonProperty("columnId")
  @ApiModelProperty(value = "")
  public Integer getColumnId() {
    return columnId;
  }

  public void setColumnId(Integer columnId) {
    this.columnId = columnId;
  }

  public CellChain cellType(String cellType) {
    this.cellType = cellType;
    return this;
  }

  /**
   * Get cellType
   * @return cellType
   **/
  @JsonProperty("cellType")
  @ApiModelProperty(value = "")
  public String getCellType() {
    return cellType;
  }

  public void setCellType(String cellType) {
    this.cellType = cellType;
  }

  public CellChain isActive(Boolean isActive) {
    this.isActive = isActive;
    return this;
  }

  /**
   * Get isActive
   * @return isActive
   **/
  @JsonProperty("isActive")
  @ApiModelProperty(value = "")
  public Boolean isIsActive() {
    return isActive;
  }

  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }

  public CellChain lastTxDetails(List<Transaction> lastTxDetails) {
    this.lastTxDetails = lastTxDetails;
    return this;
  }

  public CellChain addLastTxDetailsItem(Transaction lastTxDetailsItem) {
    if (this.lastTxDetails == null) {
      this.lastTxDetails = new ArrayList<Transaction>();
    }
    this.lastTxDetails.add(lastTxDetailsItem);
    return this;
  }

  /**
   * Get lastTxDetails
   * @return lastTxDetails
   **/
  @JsonProperty("lastTxDetails")
  @ApiModelProperty(value = "")
  public List<Transaction> getLastTxDetails() {
    return lastTxDetails;
  }

  public void setLastTxDetails(List<Transaction> lastTxDetails) {
    this.lastTxDetails = lastTxDetails;
  }

  public CellChain cellHistory(List<StringValues> cellHistory) {
    this.cellHistory = cellHistory;
    return this;
  }

  public CellChain addCellHistoryItem(StringValues cellHistoryItem) {
    if (this.cellHistory == null) {
      this.cellHistory = new ArrayList<StringValues>();
    }
    this.cellHistory.add(cellHistoryItem);
    return this;
  }

  /**
   * Get cellHistory
   * @return cellHistory
   **/
  @JsonProperty("cellHistory")
  @ApiModelProperty(value = "")
  public List<StringValues> getCellHistory() {
    return cellHistory;
  }

  public void setCellHistory(List<StringValues> cellHistory) {
    this.cellHistory = cellHistory;
  }

  public CellChain cellStatus(List<CellStatus> cellStatus) {
    this.cellStatus = cellStatus;
    return this;
  }

  public CellChain addCellStatusItem(CellStatus cellStatusItem) {
    if (this.cellStatus == null) {
      this.cellStatus = new ArrayList<CellStatus>();
    }
    this.cellStatus.add(cellStatusItem);
    return this;
  }

  /**
   * Get cellStatus
   * @return cellStatus
   **/
  @JsonProperty("cellStatus")
  @ApiModelProperty(value = "")
  public List<CellStatus> getCellStatus() {
    return cellStatus;
  }

  public void setCellStatus(List<CellStatus> cellStatus) {
    this.cellStatus = cellStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CellChain cellChain = (CellChain) o;
    return Objects.equals(this.gridId, cellChain.gridId) &&
        Objects.equals(this.cellId, cellChain.cellId) &&
        Objects.equals(this.rowId, cellChain.rowId) &&
        Objects.equals(this.columnId, cellChain.columnId) &&
        Objects.equals(this.cellType, cellChain.cellType) &&
        Objects.equals(this.isActive, cellChain.isActive) &&
        Objects.equals(this.lastTxDetails, cellChain.lastTxDetails) &&
        Objects.equals(this.cellHistory, cellChain.cellHistory) &&
        Objects.equals(this.cellStatus, cellChain.cellStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gridId, cellId, rowId, columnId, cellType, isActive, lastTxDetails, cellHistory, cellStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CellChain {\n");
    
    sb.append("    gridId: ").append(toIndentedString(gridId)).append("\n");
    sb.append("    cellId: ").append(toIndentedString(cellId)).append("\n");
    sb.append("    rowId: ").append(toIndentedString(rowId)).append("\n");
    sb.append("    columnId: ").append(toIndentedString(columnId)).append("\n");
    sb.append("    cellType: ").append(toIndentedString(cellType)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    lastTxDetails: ").append(toIndentedString(lastTxDetails)).append("\n");
    sb.append("    cellHistory: ").append(toIndentedString(cellHistory)).append("\n");
    sb.append("    cellStatus: ").append(toIndentedString(cellStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

