/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;

/**
 * LoginInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-05-26T08:31:04.295Z")
public class LoginInfo   {
  @JsonProperty("userName")
  private String userName = null;

  @JsonProperty("password")
  private String password = null;

  @JsonProperty("memberId")
  private Integer memberId = null;

  @JsonProperty("nhId")
  private Integer nhId = null;

  @JsonProperty("nhPath")
  private String nhPath = null;

  public LoginInfo userName(String userName) {
    this.userName = userName;
    return this;
  }

  /**
   * Get userName
   * @return userName
   **/
  @JsonProperty("userName")
  @ApiModelProperty(value = "")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public LoginInfo password(String password) {
    this.password = password;
    return this;
  }

  /**
   * Get password
   * @return password
   **/
  @JsonProperty("password")
  @ApiModelProperty(value = "")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public LoginInfo memberId(Integer memberId) {
    this.memberId = memberId;
    return this;
  }

  /**
   * Get memberId
   * @return memberId
   **/
  @JsonProperty("memberId")
  @ApiModelProperty(value = "")
  public Integer getMemberId() {
    return memberId;
  }

  public void setMemberId(Integer memberId) {
    this.memberId = memberId;
  }

  public LoginInfo nhId(Integer nhId) {
    this.nhId = nhId;
    return this;
  }

  /**
   * Get nhId
   * @return nhId
   **/
  @JsonProperty("nhId")
  @ApiModelProperty(value = "")
  public Integer getNhId() {
    return nhId;
  }

  public void setNhId(Integer nhId) {
    this.nhId = nhId;
  }

  public LoginInfo nhPath(String nhPath) {
    this.nhPath = nhPath;
    return this;
  }

  /**
   * Get nhPath
   * @return nhPath
   **/
  @JsonProperty("nhPath")
  @ApiModelProperty(value = "")
  public String getNhPath() {
    return nhPath;
  }

  public void setNhPath(String nhPath) {
    this.nhPath = nhPath;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginInfo loginInfo = (LoginInfo) o;
    return Objects.equals(this.userName, loginInfo.userName) &&
        Objects.equals(this.password, loginInfo.password) &&
        Objects.equals(this.memberId, loginInfo.memberId) &&
        Objects.equals(this.nhId, loginInfo.nhId) &&
        Objects.equals(this.nhPath, loginInfo.nhPath);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userName, password, memberId, nhId, nhPath);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginInfo {\n");
    
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    memberId: ").append(toIndentedString(memberId)).append("\n");
    sb.append("    nhId: ").append(toIndentedString(nhId)).append("\n");
    sb.append("    nhPath: ").append(toIndentedString(nhPath)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

