/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.1
 * Contact: apisupport@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.model.Neighborhood;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;

/**
 * Relation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-06-09T16:25:56.425Z")
public class Relation   {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("relatedNeighborhoodId")
  private List<Neighborhood> relatedNeighborhoodId = null;

  public Relation name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   **/
  @JsonProperty("name")
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Relation relatedNeighborhoodId(List<Neighborhood> relatedNeighborhoodId) {
    this.relatedNeighborhoodId = relatedNeighborhoodId;
    return this;
  }

  public Relation addRelatedNeighborhoodIdItem(Neighborhood relatedNeighborhoodIdItem) {
    if (this.relatedNeighborhoodId == null) {
      this.relatedNeighborhoodId = new ArrayList<Neighborhood>();
    }
    this.relatedNeighborhoodId.add(relatedNeighborhoodIdItem);
    return this;
  }

  /**
   * Get relatedNeighborhoodId
   * @return relatedNeighborhoodId
   **/
  @JsonProperty("relatedNeighborhoodId")
  @ApiModelProperty(value = "")
  public List<Neighborhood> getRelatedNeighborhoodId() {
    return relatedNeighborhoodId;
  }

  public void setRelatedNeighborhoodId(List<Neighborhood> relatedNeighborhoodId) {
    this.relatedNeighborhoodId = relatedNeighborhoodId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Relation relation = (Relation) o;
    return Objects.equals(this.name, relation.name) &&
        Objects.equals(this.relatedNeighborhoodId, relation.relatedNeighborhoodId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, relatedNeighborhoodId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Relation {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    relatedNeighborhoodId: ").append(toIndentedString(relatedNeighborhoodId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

