/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.2
 * Contact: apisupport@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.model.Transaction;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.validation.constraints.*;

/**
 * RowChain
 */

public class RowChain   {
  @JsonProperty("gridId")
  private Integer gridId = null;

  @JsonProperty("rowId")
  private Integer rowId = null;

  @JsonProperty("sequenceNumber")
  private Float sequenceNumber = null;

  @JsonProperty("isActive")
  private Boolean isActive = null;

  @JsonProperty("ownerId")
  private Integer ownerId = null;

  @JsonProperty("ownerEmail")
  private String ownerEmail = null;

  @JsonProperty("creationTxId")
  private Integer creationTxId = null;

  @JsonProperty("creationDateTimeGMT")
  private Long creationDateTimeGMT = null;

  @JsonProperty("creationDateTimeUTC")
  private Date creationDateTimeUTC = null;

  @JsonProperty("deletionTxId")
  private Integer deletionTxId = null;

  @JsonProperty("deletionDateTimeGMT")
  private Long deletionDateTimeGMT = null;

  @JsonProperty("deletionDateTimeUTC")
  private Date deletionDateTimeUTC = null;

  @JsonProperty("rowCreatedTxDetails")
  private List<Transaction> rowCreatedTxDetails = null;

  @JsonProperty("rowDeletedTxDetails")
  private List<Transaction> rowDeletedTxDetails = null;

  public RowChain gridId(Integer gridId) {
    this.gridId = gridId;
    return this;
  }

  /**
   * Get gridId
   * @return gridId
   **/
  @JsonProperty("gridId")
  @ApiModelProperty(value = "")
  public Integer getGridId() {
    return gridId;
  }

  public void setGridId(Integer gridId) {
    this.gridId = gridId;
  }

  public RowChain rowId(Integer rowId) {
    this.rowId = rowId;
    return this;
  }

  /**
   * Get rowId
   * @return rowId
   **/
  @JsonProperty("rowId")
  @ApiModelProperty(value = "")
  public Integer getRowId() {
    return rowId;
  }

  public void setRowId(Integer rowId) {
    this.rowId = rowId;
  }

  public RowChain sequenceNumber(Float sequenceNumber) {
    this.sequenceNumber = sequenceNumber;
    return this;
  }

  /**
   * Get sequenceNumber
   * @return sequenceNumber
   **/
  @JsonProperty("sequenceNumber")
  @ApiModelProperty(value = "")
  public Float getSequenceNumber() {
    return sequenceNumber;
  }

  public void setSequenceNumber(Float sequenceNumber) {
    this.sequenceNumber = sequenceNumber;
  }

  public RowChain isActive(Boolean isActive) {
    this.isActive = isActive;
    return this;
  }

  /**
   * Get isActive
   * @return isActive
   **/
  @JsonProperty("isActive")
  @ApiModelProperty(value = "")
  public Boolean isIsActive() {
    return isActive;
  }

  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }

  public RowChain ownerId(Integer ownerId) {
    this.ownerId = ownerId;
    return this;
  }

  /**
   * Get ownerId
   * @return ownerId
   **/
  @JsonProperty("ownerId")
  @ApiModelProperty(value = "")
  public Integer getOwnerId() {
    return ownerId;
  }

  public void setOwnerId(Integer ownerId) {
    this.ownerId = ownerId;
  }

  public RowChain ownerEmail(String ownerEmail) {
    this.ownerEmail = ownerEmail;
    return this;
  }

  /**
   * Get ownerEmail
   * @return ownerEmail
   **/
  @JsonProperty("ownerEmail")
  @ApiModelProperty(value = "")
  public String getOwnerEmail() {
    return ownerEmail;
  }

  public void setOwnerEmail(String ownerEmail) {
    this.ownerEmail = ownerEmail;
  }

  public RowChain creationTxId(Integer creationTxId) {
    this.creationTxId = creationTxId;
    return this;
  }

  /**
   * Get creationTxId
   * @return creationTxId
   **/
  @JsonProperty("creationTxId")
  @ApiModelProperty(value = "")
  public Integer getCreationTxId() {
    return creationTxId;
  }

  public void setCreationTxId(Integer creationTxId) {
    this.creationTxId = creationTxId;
  }

  public RowChain creationDateTimeGMT(Long creationDateTimeGMT) {
    this.creationDateTimeGMT = creationDateTimeGMT;
    return this;
  }

  /**
   * Get creationDateTimeGMT
   * @return creationDateTimeGMT
   **/
  @JsonProperty("creationDateTimeGMT")
  @ApiModelProperty(value = "")
  public Long getCreationDateTimeGMT() {
    return creationDateTimeGMT;
  }

  public void setCreationDateTimeGMT(Long creationDateTimeGMT) {
    this.creationDateTimeGMT = creationDateTimeGMT;
  }

  public RowChain creationDateTimeUTC(Date creationDateTimeUTC) {
    this.creationDateTimeUTC = creationDateTimeUTC;
    return this;
  }

  /**
   * Get creationDateTimeUTC
   * @return creationDateTimeUTC
   **/
  @JsonProperty("creationDateTimeUTC")
  @ApiModelProperty(value = "")
  public Date getCreationDateTimeUTC() {
    return creationDateTimeUTC;
  }

  public void setCreationDateTimeUTC(Date creationDateTimeUTC) {
    this.creationDateTimeUTC = creationDateTimeUTC;
  }

  public RowChain deletionTxId(Integer deletionTxId) {
    this.deletionTxId = deletionTxId;
    return this;
  }

  /**
   * Get deletionTxId
   * @return deletionTxId
   **/
  @JsonProperty("deletionTxId")
  @ApiModelProperty(value = "")
  public Integer getDeletionTxId() {
    return deletionTxId;
  }

  public void setDeletionTxId(Integer deletionTxId) {
    this.deletionTxId = deletionTxId;
  }

  public RowChain deletionDateTimeGMT(Long deletionDateTimeGMT) {
    this.deletionDateTimeGMT = deletionDateTimeGMT;
    return this;
  }

  /**
   * Get deletionDateTimeGMT
   * @return deletionDateTimeGMT
   **/
  @JsonProperty("deletionDateTimeGMT")
  @ApiModelProperty(value = "")
  public Long getDeletionDateTimeGMT() {
    return deletionDateTimeGMT;
  }

  public void setDeletionDateTimeGMT(Long deletionDateTimeGMT) {
    this.deletionDateTimeGMT = deletionDateTimeGMT;
  }

  public RowChain deletionDateTimeUTC(Date deletionDateTimeUTC) {
    this.deletionDateTimeUTC = deletionDateTimeUTC;
    return this;
  }

  /**
   * Get deletionDateTimeUTC
   * @return deletionDateTimeUTC
   **/
  @JsonProperty("deletionDateTimeUTC")
  @ApiModelProperty(value = "")
  public Date getDeletionDateTimeUTC() {
    return deletionDateTimeUTC;
  }

  public void setDeletionDateTimeUTC(Date deletionDateTimeUTC) {
    this.deletionDateTimeUTC = deletionDateTimeUTC;
  }

  public RowChain rowCreatedTxDetails(List<Transaction> rowCreatedTxDetails) {
    this.rowCreatedTxDetails = rowCreatedTxDetails;
    return this;
  }

  public RowChain addRowCreatedTxDetailsItem(Transaction rowCreatedTxDetailsItem) {
    if (this.rowCreatedTxDetails == null) {
      this.rowCreatedTxDetails = new ArrayList<Transaction>();
    }
    this.rowCreatedTxDetails.add(rowCreatedTxDetailsItem);
    return this;
  }

  /**
   * Get rowCreatedTxDetails
   * @return rowCreatedTxDetails
   **/
  @JsonProperty("rowCreatedTxDetails")
  @ApiModelProperty(value = "")
  public List<Transaction> getRowCreatedTxDetails() {
    return rowCreatedTxDetails;
  }

  public void setRowCreatedTxDetails(List<Transaction> rowCreatedTxDetails) {
    this.rowCreatedTxDetails = rowCreatedTxDetails;
  }

  public RowChain rowDeletedTxDetails(List<Transaction> rowDeletedTxDetails) {
    this.rowDeletedTxDetails = rowDeletedTxDetails;
    return this;
  }

  public RowChain addRowDeletedTxDetailsItem(Transaction rowDeletedTxDetailsItem) {
    if (this.rowDeletedTxDetails == null) {
      this.rowDeletedTxDetails = new ArrayList<Transaction>();
    }
    this.rowDeletedTxDetails.add(rowDeletedTxDetailsItem);
    return this;
  }

  /**
   * Get rowDeletedTxDetails
   * @return rowDeletedTxDetails
   **/
  @JsonProperty("rowDeletedTxDetails")
  @ApiModelProperty(value = "")
  public List<Transaction> getRowDeletedTxDetails() {
    return rowDeletedTxDetails;
  }

  public void setRowDeletedTxDetails(List<Transaction> rowDeletedTxDetails) {
    this.rowDeletedTxDetails = rowDeletedTxDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RowChain rowChain = (RowChain) o;
    return Objects.equals(this.gridId, rowChain.gridId) &&
        Objects.equals(this.rowId, rowChain.rowId) &&
        Objects.equals(this.sequenceNumber, rowChain.sequenceNumber) &&
        Objects.equals(this.isActive, rowChain.isActive) &&
        Objects.equals(this.ownerId, rowChain.ownerId) &&
        Objects.equals(this.ownerEmail, rowChain.ownerEmail) &&
        Objects.equals(this.creationTxId, rowChain.creationTxId) &&
        Objects.equals(this.creationDateTimeGMT, rowChain.creationDateTimeGMT) &&
        Objects.equals(this.creationDateTimeUTC, rowChain.creationDateTimeUTC) &&
        Objects.equals(this.deletionTxId, rowChain.deletionTxId) &&
        Objects.equals(this.deletionDateTimeGMT, rowChain.deletionDateTimeGMT) &&
        Objects.equals(this.deletionDateTimeUTC, rowChain.deletionDateTimeUTC) &&
        Objects.equals(this.rowCreatedTxDetails, rowChain.rowCreatedTxDetails) &&
        Objects.equals(this.rowDeletedTxDetails, rowChain.rowDeletedTxDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gridId, rowId, sequenceNumber, isActive, ownerId, ownerEmail, creationTxId, creationDateTimeGMT, creationDateTimeUTC, deletionTxId, deletionDateTimeGMT, deletionDateTimeUTC, rowCreatedTxDetails, rowDeletedTxDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RowChain {\n");
    
    sb.append("    gridId: ").append(toIndentedString(gridId)).append("\n");
    sb.append("    rowId: ").append(toIndentedString(rowId)).append("\n");
    sb.append("    sequenceNumber: ").append(toIndentedString(sequenceNumber)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    ownerEmail: ").append(toIndentedString(ownerEmail)).append("\n");
    sb.append("    creationTxId: ").append(toIndentedString(creationTxId)).append("\n");
    sb.append("    creationDateTimeGMT: ").append(toIndentedString(creationDateTimeGMT)).append("\n");
    sb.append("    creationDateTimeUTC: ").append(toIndentedString(creationDateTimeUTC)).append("\n");
    sb.append("    deletionTxId: ").append(toIndentedString(deletionTxId)).append("\n");
    sb.append("    deletionDateTimeGMT: ").append(toIndentedString(deletionDateTimeGMT)).append("\n");
    sb.append("    deletionDateTimeUTC: ").append(toIndentedString(deletionDateTimeUTC)).append("\n");
    sb.append("    rowCreatedTxDetails: ").append(toIndentedString(rowCreatedTxDetails)).append("\n");
    sb.append("    rowDeletedTxDetails: ").append(toIndentedString(rowDeletedTxDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

