/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.2
 * Contact: apisupport@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;
import javax.validation.constraints.*;

/**
 * StatusChange
 */

public class StatusChange   {
  @JsonProperty("rowId")
  private Integer rowId = null;

  @JsonProperty("columnId")
  private Integer columnId = null;

  @JsonProperty("active")
  private Boolean active = null;

  @JsonProperty("txId")
  private Integer txId = null;

  @JsonProperty("createdDateTime")
  private Long createdDateTime = null;

  @JsonProperty("creationDateTimeUTC")
  private Date creationDateTimeUTC = null;

  @JsonProperty("comment")
  private String comment = null;

  @JsonProperty("userEmail")
  private String userEmail = null;

  @JsonProperty("columnSeq")
  private Float columnSeq = null;

  @JsonProperty("rowSeq")
  private Float rowSeq = null;

  public StatusChange rowId(Integer rowId) {
    this.rowId = rowId;
    return this;
  }

  /**
   * Get rowId
   * @return rowId
   **/
  @JsonProperty("rowId")
  @ApiModelProperty(value = "")
  public Integer getRowId() {
    return rowId;
  }

  public void setRowId(Integer rowId) {
    this.rowId = rowId;
  }

  public StatusChange columnId(Integer columnId) {
    this.columnId = columnId;
    return this;
  }

  /**
   * Get columnId
   * @return columnId
   **/
  @JsonProperty("columnId")
  @ApiModelProperty(value = "")
  public Integer getColumnId() {
    return columnId;
  }

  public void setColumnId(Integer columnId) {
    this.columnId = columnId;
  }

  public StatusChange active(Boolean active) {
    this.active = active;
    return this;
  }

  /**
   * Get active
   * @return active
   **/
  @JsonProperty("active")
  @ApiModelProperty(value = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public StatusChange txId(Integer txId) {
    this.txId = txId;
    return this;
  }

  /**
   * Get txId
   * @return txId
   **/
  @JsonProperty("txId")
  @ApiModelProperty(value = "")
  public Integer getTxId() {
    return txId;
  }

  public void setTxId(Integer txId) {
    this.txId = txId;
  }

  public StatusChange createdDateTime(Long createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

  /**
   * Get createdDateTime
   * @return createdDateTime
   **/
  @JsonProperty("createdDateTime")
  @ApiModelProperty(value = "")
  public Long getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(Long createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public StatusChange creationDateTimeUTC(Date creationDateTimeUTC) {
    this.creationDateTimeUTC = creationDateTimeUTC;
    return this;
  }

  /**
   * Get creationDateTimeUTC
   * @return creationDateTimeUTC
   **/
  @JsonProperty("creationDateTimeUTC")
  @ApiModelProperty(value = "")
  public Date getCreationDateTimeUTC() {
    return creationDateTimeUTC;
  }

  public void setCreationDateTimeUTC(Date creationDateTimeUTC) {
    this.creationDateTimeUTC = creationDateTimeUTC;
  }

  public StatusChange comment(String comment) {
    this.comment = comment;
    return this;
  }

  /**
   * Get comment
   * @return comment
   **/
  @JsonProperty("comment")
  @ApiModelProperty(value = "")
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public StatusChange userEmail(String userEmail) {
    this.userEmail = userEmail;
    return this;
  }

  /**
   * Get userEmail
   * @return userEmail
   **/
  @JsonProperty("userEmail")
  @ApiModelProperty(value = "")
  public String getUserEmail() {
    return userEmail;
  }

  public void setUserEmail(String userEmail) {
    this.userEmail = userEmail;
  }

  public StatusChange columnSeq(Float columnSeq) {
    this.columnSeq = columnSeq;
    return this;
  }

  /**
   * Get columnSeq
   * @return columnSeq
   **/
  @JsonProperty("columnSeq")
  @ApiModelProperty(value = "")
  public Float getColumnSeq() {
    return columnSeq;
  }

  public void setColumnSeq(Float columnSeq) {
    this.columnSeq = columnSeq;
  }

  public StatusChange rowSeq(Float rowSeq) {
    this.rowSeq = rowSeq;
    return this;
  }

  /**
   * Get rowSeq
   * @return rowSeq
   **/
  @JsonProperty("rowSeq")
  @ApiModelProperty(value = "")
  public Float getRowSeq() {
    return rowSeq;
  }

  public void setRowSeq(Float rowSeq) {
    this.rowSeq = rowSeq;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatusChange statusChange = (StatusChange) o;
    return Objects.equals(this.rowId, statusChange.rowId) &&
        Objects.equals(this.columnId, statusChange.columnId) &&
        Objects.equals(this.active, statusChange.active) &&
        Objects.equals(this.txId, statusChange.txId) &&
        Objects.equals(this.createdDateTime, statusChange.createdDateTime) &&
        Objects.equals(this.creationDateTimeUTC, statusChange.creationDateTimeUTC) &&
        Objects.equals(this.comment, statusChange.comment) &&
        Objects.equals(this.userEmail, statusChange.userEmail) &&
        Objects.equals(this.columnSeq, statusChange.columnSeq) &&
        Objects.equals(this.rowSeq, statusChange.rowSeq);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rowId, columnId, active, txId, createdDateTime, creationDateTimeUTC, comment, userEmail, columnSeq, rowSeq);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatusChange {\n");
    
    sb.append("    rowId: ").append(toIndentedString(rowId)).append("\n");
    sb.append("    columnId: ").append(toIndentedString(columnId)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    txId: ").append(toIndentedString(txId)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    creationDateTimeUTC: ").append(toIndentedString(creationDateTimeUTC)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    userEmail: ").append(toIndentedString(userEmail)).append("\n");
    sb.append("    columnSeq: ").append(toIndentedString(columnSeq)).append("\n");
    sb.append("    rowSeq: ").append(toIndentedString(rowSeq)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

