/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.2
 * Contact: apisupport@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.model.StringValuesStrValueFormula;
import io.swagger.model.Transaction;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;

/**
 * StringValues
 */

public class StringValues   {
  @JsonProperty("cellId")
  private Integer cellId = null;

  @JsonProperty("stringValueId")
  private Integer stringValueId = null;

  @JsonProperty("stringValue")
  private String stringValue = null;

  @JsonProperty("strValueTransaction")
  private List<Transaction> strValueTransaction = null;

  @JsonProperty("strValueFormula")
  private StringValuesStrValueFormula strValueFormula = null;

  public StringValues cellId(Integer cellId) {
    this.cellId = cellId;
    return this;
  }

  /**
   * Get cellId
   * @return cellId
   **/
  @JsonProperty("cellId")
  @ApiModelProperty(value = "")
  public Integer getCellId() {
    return cellId;
  }

  public void setCellId(Integer cellId) {
    this.cellId = cellId;
  }

  public StringValues stringValueId(Integer stringValueId) {
    this.stringValueId = stringValueId;
    return this;
  }

  /**
   * Get stringValueId
   * @return stringValueId
   **/
  @JsonProperty("stringValueId")
  @ApiModelProperty(value = "")
  public Integer getStringValueId() {
    return stringValueId;
  }

  public void setStringValueId(Integer stringValueId) {
    this.stringValueId = stringValueId;
  }

  public StringValues stringValue(String stringValue) {
    this.stringValue = stringValue;
    return this;
  }

  /**
   * Get stringValue
   * @return stringValue
   **/
  @JsonProperty("stringValue")
  @ApiModelProperty(value = "")
  public String getStringValue() {
    return stringValue;
  }

  public void setStringValue(String stringValue) {
    this.stringValue = stringValue;
  }

  public StringValues strValueTransaction(List<Transaction> strValueTransaction) {
    this.strValueTransaction = strValueTransaction;
    return this;
  }

  public StringValues addStrValueTransactionItem(Transaction strValueTransactionItem) {
    if (this.strValueTransaction == null) {
      this.strValueTransaction = new ArrayList<Transaction>();
    }
    this.strValueTransaction.add(strValueTransactionItem);
    return this;
  }

  /**
   * Get strValueTransaction
   * @return strValueTransaction
   **/
  @JsonProperty("strValueTransaction")
  @ApiModelProperty(value = "")
  public List<Transaction> getStrValueTransaction() {
    return strValueTransaction;
  }

  public void setStrValueTransaction(List<Transaction> strValueTransaction) {
    this.strValueTransaction = strValueTransaction;
  }

  public StringValues strValueFormula(StringValuesStrValueFormula strValueFormula) {
    this.strValueFormula = strValueFormula;
    return this;
  }

  /**
   * Get strValueFormula
   * @return strValueFormula
   **/
  @JsonProperty("strValueFormula")
  @ApiModelProperty(value = "")
  public StringValuesStrValueFormula getStrValueFormula() {
    return strValueFormula;
  }

  public void setStrValueFormula(StringValuesStrValueFormula strValueFormula) {
    this.strValueFormula = strValueFormula;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StringValues stringValues = (StringValues) o;
    return Objects.equals(this.cellId, stringValues.cellId) &&
        Objects.equals(this.stringValueId, stringValues.stringValueId) &&
        Objects.equals(this.stringValue, stringValues.stringValue) &&
        Objects.equals(this.strValueTransaction, stringValues.strValueTransaction) &&
        Objects.equals(this.strValueFormula, stringValues.strValueFormula);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cellId, stringValueId, stringValue, strValueTransaction, strValueFormula);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StringValues {\n");
    
    sb.append("    cellId: ").append(toIndentedString(cellId)).append("\n");
    sb.append("    stringValueId: ").append(toIndentedString(stringValueId)).append("\n");
    sb.append("    stringValue: ").append(toIndentedString(stringValue)).append("\n");
    sb.append("    strValueTransaction: ").append(toIndentedString(strValueTransaction)).append("\n");
    sb.append("    strValueFormula: ").append(toIndentedString(strValueFormula)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

