/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.2
 * Contact: apisupport@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.model.GridNames;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;

/**
 * Whiteboard
 */

public class Whiteboard   {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("gridList")
  private List<GridNames> gridList = null;

  public Whiteboard id(Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   **/
  @JsonProperty("id")
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Whiteboard name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   **/
  @JsonProperty("name")
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Whiteboard gridList(List<GridNames> gridList) {
    this.gridList = gridList;
    return this;
  }

  public Whiteboard addGridListItem(GridNames gridListItem) {
    if (this.gridList == null) {
      this.gridList = new ArrayList<GridNames>();
    }
    this.gridList.add(gridListItem);
    return this;
  }

  /**
   * Get gridList
   * @return gridList
   **/
  @JsonProperty("gridList")
  @ApiModelProperty(value = "")
  public List<GridNames> getGridList() {
    return gridList;
  }

  public void setGridList(List<GridNames> gridList) {
    this.gridList = gridList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Whiteboard whiteboard = (Whiteboard) o;
    return Objects.equals(this.id, whiteboard.id) &&
        Objects.equals(this.name, whiteboard.name) &&
        Objects.equals(this.gridList, whiteboard.gridList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, gridList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Whiteboard {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    gridList: ").append(toIndentedString(gridList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

