
SELECT BW_NH_LEVEL_0.ID, BW_NH_LEVEL_0.NAME,BW_NH_LEVEL_0.NEIGHBORHOOD_ID,BW_NH.IS_SECURE  
FROM   BW_NH_LEVEL_0, BW_NH, BW_TXS 
WHERE  BW_NH_LEVEL_0.NEIGHBORHOOD_ID = BW_NH.ID  
AND    BW_NH.IS_ACTIVE=1
UNION
SELECT BW_NH_LEVEL_0.ID, BW_NH_LEVEL_0.NAME,BW_NH_LEVEL_0.NEIGHBORHOOD_ID,BW_NH.IS_SECURE  
FROM   BW_NH_LEVEL_0, BW_NH, BW_TXS 
WHERE  BW_NH_LEVEL_0.NEIGHBORHOOD_ID = BW_NH.ID  
AND    BW_NH.IS_ACTIVE=1
AND    BW_NH.MANAGED_BY = ?
