Select BW_NH.ID, BW_NH.NAME, BW_NH_REL.REL 
from BW_NH_REL, BW_NH, BW_TBL
WHERE BW_NH_REL.NEIGHBORHOOD_ID = BW_TBL.NEIGHBORHOOD_ID
  AND BW_NH_REL.TARGET_NH_ID = BW_NH.ID
AND BW_TBL.ID = ?
ORDER BY BW_NH_REL.REL