			
SELECT 	BW_TBL.IS_LOCKED, 
	BW_TBL.LOCK_TX_ID, 
	BW_USER.ID   LOCKED_BY_ID, 
	BW_USER.EMAIL_ADDRESS   LOCKED_BY, 
	BW_TXS.CREATED_ON   LOCK_UNLOCK_TIME
FROM 	BW_TBL,
	BW_TXS, 
	BW_USER		
WHERE 	BW_TBL.ID = ?
	AND BW_TXS.TX_ID = BW_TBL.LOCK_TX_ID
	AND BW_USER.ID = BW_TXS.CREATED_BY