SELECT 	BWCOLUMN.ID   COLUMN_ID, 
	BWCOLUMN.NAME   COLUMN_NAME, 
	BWCOLUMN.COLUMN_TYPE   COLUMN_TYPE, 
	BWCOLUMN.SEQUENCE_NUMBER   COLUMN_SEQUENCE_NUMBER, 
	BWCOLUMN.DEFAULT_STRING_VALUE, 
	BWCOLUMN.DEFAULT_INTEGER_VALUE, 
	BWCOLUMN.DEFAULT_FLOAT_VALUE, 
	BWCOLUMN.DEAFULT_TBL_VALUE, 
	BWCOLUMN.IS_ENUMERATED, 
	BWCOLUMN.LOOKUP_TBL_ID, 
	BWCOLUMN.LOOKUP_COLUMN_ID, 
	BW_LOOKUP_CELL.STRING_VALUE   LOOKUP_STRING_VALUE,
	BW_LOOKUP_CELL.INTEGER_VALUE   LOOKUP_INTEGER_VALUE,
	BW_LOOKUP_CELL.DOUBLE_VALUE   LOOKUP_DOUBLE_VALUE,
	BW_LOOKUP_CELL.TABLE_VALUE   LOOKUP_TBL_VALUE, 
	'Not set' LOOKUP_TBL_NAME,
	'LATEST' LKP_TBL_VIEW_PREF_TYPE,
	BW_LOOKUP_CELL.BW_ROW_ID, 
	BWCOLUMN.TX_ID   COL_TID, 
	BWCOLUMN.IS_ACTIVE   COL_ACTIVE,
	-1 ORDERED_LIST_TBL_ID, 
	-1 ORDERED_LIST_TBL_COLUMN_ID, 
	'LOOKUP' ORDER_TYPE, 
	'NOTSET' ORDERED_TBL_NAME,  
	LOOKUP_TABLE.NAME   LOOKUP_TBLNAME,
	BW_LOOKUP_ROW.SEQUENCE_NUMBER   ROW_SEQUENCE_NUMBER
FROM 	
	BW_TBL   LOOKUP_TABLE,
	BW_COLUMN   BWCOLUMN, 
	BW_COLUMN   BW_LOOKUP_COLUMN, 
	BW_CELL   BW_LOOKUP_CELL,
	BW_ROW   BW_LOOKUP_ROW
WHERE 	BWCOLUMN.BW_TBL_ID = ?
      	AND BWCOLUMN.LOOKUP_COLUMN_ID = BW_LOOKUP_COLUMN.ID
      	AND BW_LOOKUP_CELL.BW_COLUMN_ID = BW_LOOKUP_COLUMN.ID
    	AND BWCOLUMN.ID NOT IN 
	(
		SELECT  BW_COLUMN_ORDERED_TBL.COLUMN_ID
		FROM BW_COLUMN_ORDERED_TBL
	)
	AND LOOKUP_TABLE.ID = BWCOLUMN.LOOKUP_TBL_ID
	AND BW_LOOKUP_ROW.ID = BW_LOOKUP_CELL.BW_ROW_ID
	AND BW_LOOKUP_ROW.IS_ACTIVE = 1
UNION ALL 
SELECT 	BWCOLUMN.ID   COLUMN_ID, 
	BWCOLUMN.NAME   COLUMN_NAME, 
	BWCOLUMN.COLUMN_TYPE   COLUMN_TYPE, 
	BWCOLUMN.SEQUENCE_NUMBER   COLUMN_SEQUENCE_NUMBER, 
	BWCOLUMN.DEFAULT_STRING_VALUE, 
	BWCOLUMN.DEFAULT_INTEGER_VALUE, 
	BWCOLUMN.DEFAULT_FLOAT_VALUE, 
	BWCOLUMN.DEAFULT_TBL_VALUE, 
	BWCOLUMN.IS_ENUMERATED, 
	BWCOLUMN.LOOKUP_TBL_ID, 
	BWCOLUMN.LOOKUP_COLUMN_ID, 
	'-1' LOOKUP_STRING_VALUE, 
	-1 LOOKUP_INTEGER_VALUE, 
	1.1 LOOKUP_DOUBLE_VALUE, 
	-1 LOOKUP_TBL_VALUE, 
	'Not set' LOOKUP_TBL_NAME, 
	'XYZ' LKP_TBL_VIEW_PREF_TYPE,
	-1 BW_ROW_ID, 
	BWCOLUMN.TX_ID   COL_TID, 
	BWCOLUMN.IS_ACTIVE,
	-1 ORDERED_LIST_TBL_ID, 
	-1 ORDERED_LIST_TBL_COLUMN_ID, 
	'NORMAL' ORDER_TYPE,
	'NOTSET' ORDERED_TBL_NAME , 
	'NOTSET' LOOKUP_TBLNAME  ,
	-1 ROW_SEQUENCE_NUMBER
FROM 	BW_COLUMN   BWCOLUMN
WHERE 	BWCOLUMN.BW_TBL_ID = ?
	AND BWCOLUMN.IS_ENUMERATED != 1
	AND BWCOLUMN.ID NOT IN 
	(
		SELECT  BW_COLUMN_ORDERED_TBL.COLUMN_ID
		FROM BW_COLUMN_ORDERED_TBL
	)
UNION ALL 
SELECT
	BWCOLUMN.ID   COLUMN_ID, 
	BWCOLUMN.NAME   COLUMN_NAME, 
	BWCOLUMN.COLUMN_TYPE   COLUMN_TYPE, 
	BWCOLUMN.SEQUENCE_NUMBER   COLUMN_SEQUENCE_NUMBER, 
	BWCOLUMN.DEFAULT_STRING_VALUE,
	BWCOLUMN.DEFAULT_INTEGER_VALUE, 
	BWCOLUMN.DEFAULT_FLOAT_VALUE, 
	BWCOLUMN.DEAFULT_TBL_VALUE, 
	BWCOLUMN.IS_ENUMERATED, 
	BWCOLUMN.LOOKUP_TBL_ID,
	BWCOLUMN.LOOKUP_COLUMN_ID, 
	'-1' LOOKUP_STRING_VALUE, 
	-1 LOOKUP_INTEGER_VALUE, 
	1.1 LOOKUP_DOUBLE_VALUE, 
	-1 LOOKUP_TBL_VALUE, 
	'Not set' LOOKUP_TBL_NAME, 
	'XYZ' LKP_TBL_VIEW_PREF_TYPE,
	-1 BW_ROW_ID, 
	BWCOLUMN.TX_ID   COL_TID, 
	BWCOLUMN.IS_ACTIVE,
	BW_ORDERED_COLUMN.ORDERED_LIST_TBL_ID, 
	BW_ORDERED_COLUMN.ORDERED_LIST_TBL_COLUMN_ID,
	BW_ORDERED_COLUMN.ORDER_TYPE, 
	ORDERED_COL_TABLE.NAME , 
	'NOTSET' LOOKUP_TBLNAME,
	-1 ROW_SEQUENCE_NUMBER
FROM 
	BW_TBL   ORDERED_COL_TABLE,
	BW_COLUMN   BWCOLUMN,  
	BW_COLUMN_ORDERED_TBL   BW_ORDERED_COLUMN
WHERE
	BWCOLUMN.BW_TBL_ID = ?
	AND BWCOLUMN.ID = BW_ORDERED_COLUMN.COLUMN_ID
	AND BWCOLUMN.IS_ENUMERATED != 1
	AND ORDERED_COL_TABLE.ID = BW_ORDERED_COLUMN.ORDERED_LIST_TBL_ID
UNION ALL 
SELECT 	BWCOLUMN.ID   COLUMN_ID, 
	BWCOLUMN.NAME   COLUMN_NAME,
	BWCOLUMN.COLUMN_TYPE   COLUMN_TYPE, 
	BWCOLUMN.SEQUENCE_NUMBER   COLUMN_SEQUENCE_NUMBER, 
	BWCOLUMN.DEFAULT_STRING_VALUE, 
	BWCOLUMN.DEFAULT_INTEGER_VALUE, 
	BWCOLUMN.DEFAULT_FLOAT_VALUE, 
	BWCOLUMN.DEAFULT_TBL_VALUE, 
	BWCOLUMN.IS_ENUMERATED, 
	BWCOLUMN.LOOKUP_TBL_ID,
	BWCOLUMN.LOOKUP_COLUMN_ID, 
	BW_LOOKUP_CELL.STRING_VALUE   LOOKUP_STRING_VALUE,
	BW_LOOKUP_CELL.INTEGER_VALUE   LOOKUP_INTEGER_VALUE,
	BW_LOOKUP_CELL.DOUBLE_VALUE   LOOKUP_DOUBLE_VALUE,
	BW_LOOKUP_CELL.TABLE_VALUE   LOOKUP_TBL_VALUE,  
	'Not set' LOOKUP_TBL_NAME,
	'LATEST' LKP_TBL_VIEW_PREF_TYPE,
	BW_LOOKUP_CELL.BW_ROW_ID, 
	BWCOLUMN.TX_ID   COL_TID, 
	BWCOLUMN.IS_ACTIVE   COL_ACTIVE,
	BW_OCL.ORDERED_LIST_TBL_ID, 
	BW_OCL.ORDERED_LIST_TBL_COLUMN_ID, 
	BW_OCL.ORDER_TYPE,
	ORDERED_TBL_NAMES.NAME   ORDERED_TBL_NAME, 
	LOOKUP_TBL_NAMES.NAME   LOOKUP_TBLNAME,
	BW_LOOKUP_ROW.SEQUENCE_NUMBER   ROW_SEQUENCE_NUMBER
FROM 	
	BW_TBL   LOOKUP_TBL_NAMES,
	BW_TBL   ORDERED_TBL_NAMES,
	BW_COLUMN   BWCOLUMN, 
	BW_COLUMN   BW_LOOKUP_COLUMN, 
	BW_CELL   BW_LOOKUP_CELL,
	BW_COLUMN_ORDERED_TBL   BW_OCL,
	BW_ROW   BW_LOOKUP_ROW
WHERE 
	BWCOLUMN.BW_TBL_ID = ?
	AND BWCOLUMN.LOOKUP_COLUMN_ID = BW_LOOKUP_COLUMN.ID
	AND BW_LOOKUP_CELL.BW_COLUMN_ID = BW_LOOKUP_COLUMN.ID
	AND BWCOLUMN.ID =  BW_OCL.COLUMN_ID
	AND  ORDERED_TBL_NAMES.ID = BW_OCL.ORDERED_LIST_TBL_ID
	AND LOOKUP_TBL_NAMES.ID = BWCOLUMN.LOOKUP_TBL_ID
	AND BW_LOOKUP_ROW.ID = BW_LOOKUP_CELL.BW_ROW_ID
	AND BW_LOOKUP_ROW.IS_ACTIVE = 1
ORDER BY COLUMN_SEQUENCE_NUMBER, ROW_SEQUENCE_NUMBER