/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;

/**
 * GridChangeBuffer
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-05-06T17:48:54.305Z")
public class GridChangeBuffer   {
  @JsonProperty("newRowdArray")
  private List<Integer> newRowdArray = null;

  @JsonProperty("deletedRowArray")
  private List<Integer> deletedRowArray = null;

  @JsonProperty("newColumnArray")
  private List<Integer> newColumnArray = null;

  @JsonProperty("deletedColumnArray")
  private List<Integer> deletedColumnArray = null;

  public GridChangeBuffer newRowdArray(List<Integer> newRowdArray) {
    this.newRowdArray = newRowdArray;
    return this;
  }

  public GridChangeBuffer addNewRowdArrayItem(Integer newRowdArrayItem) {
    if (this.newRowdArray == null) {
      this.newRowdArray = new ArrayList<Integer>();
    }
    this.newRowdArray.add(newRowdArrayItem);
    return this;
  }

  /**
   * Get newRowdArray
   * @return newRowdArray
   **/
  @JsonProperty("newRowdArray")
  @ApiModelProperty(value = "")
  public List<Integer> getNewRowdArray() {
    return newRowdArray;
  }

  public void setNewRowdArray(List<Integer> newRowdArray) {
    this.newRowdArray = newRowdArray;
  }

  public GridChangeBuffer deletedRowArray(List<Integer> deletedRowArray) {
    this.deletedRowArray = deletedRowArray;
    return this;
  }

  public GridChangeBuffer addDeletedRowArrayItem(Integer deletedRowArrayItem) {
    if (this.deletedRowArray == null) {
      this.deletedRowArray = new ArrayList<Integer>();
    }
    this.deletedRowArray.add(deletedRowArrayItem);
    return this;
  }

  /**
   * Get deletedRowArray
   * @return deletedRowArray
   **/
  @JsonProperty("deletedRowArray")
  @ApiModelProperty(value = "")
  public List<Integer> getDeletedRowArray() {
    return deletedRowArray;
  }

  public void setDeletedRowArray(List<Integer> deletedRowArray) {
    this.deletedRowArray = deletedRowArray;
  }

  public GridChangeBuffer newColumnArray(List<Integer> newColumnArray) {
    this.newColumnArray = newColumnArray;
    return this;
  }

  public GridChangeBuffer addNewColumnArrayItem(Integer newColumnArrayItem) {
    if (this.newColumnArray == null) {
      this.newColumnArray = new ArrayList<Integer>();
    }
    this.newColumnArray.add(newColumnArrayItem);
    return this;
  }

  /**
   * Get newColumnArray
   * @return newColumnArray
   **/
  @JsonProperty("newColumnArray")
  @ApiModelProperty(value = "")
  public List<Integer> getNewColumnArray() {
    return newColumnArray;
  }

  public void setNewColumnArray(List<Integer> newColumnArray) {
    this.newColumnArray = newColumnArray;
  }

  public GridChangeBuffer deletedColumnArray(List<Integer> deletedColumnArray) {
    this.deletedColumnArray = deletedColumnArray;
    return this;
  }

  public GridChangeBuffer addDeletedColumnArrayItem(Integer deletedColumnArrayItem) {
    if (this.deletedColumnArray == null) {
      this.deletedColumnArray = new ArrayList<Integer>();
    }
    this.deletedColumnArray.add(deletedColumnArrayItem);
    return this;
  }

  /**
   * Get deletedColumnArray
   * @return deletedColumnArray
   **/
  @JsonProperty("deletedColumnArray")
  @ApiModelProperty(value = "")
  public List<Integer> getDeletedColumnArray() {
    return deletedColumnArray;
  }

  public void setDeletedColumnArray(List<Integer> deletedColumnArray) {
    this.deletedColumnArray = deletedColumnArray;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GridChangeBuffer gridChangeBuffer = (GridChangeBuffer) o;
    return Objects.equals(this.newRowdArray, gridChangeBuffer.newRowdArray) &&
        Objects.equals(this.deletedRowArray, gridChangeBuffer.deletedRowArray) &&
        Objects.equals(this.newColumnArray, gridChangeBuffer.newColumnArray) &&
        Objects.equals(this.deletedColumnArray, gridChangeBuffer.deletedColumnArray);
  }

  @Override
  public int hashCode() {
    return Objects.hash(newRowdArray, deletedRowArray, newColumnArray, deletedColumnArray);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GridChangeBuffer {\n");
    
    sb.append("    newRowdArray: ").append(toIndentedString(newRowdArray)).append("\n");
    sb.append("    deletedRowArray: ").append(toIndentedString(deletedRowArray)).append("\n");
    sb.append("    newColumnArray: ").append(toIndentedString(newColumnArray)).append("\n");
    sb.append("    deletedColumnArray: ").append(toIndentedString(deletedColumnArray)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

