/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;

/**
 * Row
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-04-27T06:34:45.359Z")
public class Row   {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("seqNo")
  private Integer seqNo = null;

  @JsonProperty("previousRowid")
  private Integer previousRowid = null;

  @JsonProperty("previousRowSequence")
  private Integer previousRowSequence = null;

  @JsonProperty("active")
  private Boolean active = null;

  @JsonProperty("tid")
  private Integer tid = null;

  public Row id(Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   **/
  @JsonProperty("id")
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Row seqNo(Integer seqNo) {
    this.seqNo = seqNo;
    return this;
  }

  /**
   * Get seqNo
   * @return seqNo
   **/
  @JsonProperty("seqNo")
  @ApiModelProperty(value = "")
  public Integer getSeqNo() {
    return seqNo;
  }

  public void setSeqNo(Integer seqNo) {
    this.seqNo = seqNo;
  }

  public Row previousRowid(Integer previousRowid) {
    this.previousRowid = previousRowid;
    return this;
  }

  /**
   * Get previousRowid
   * @return previousRowid
   **/
  @JsonProperty("previousRowid")
  @ApiModelProperty(value = "")
  public Integer getPreviousRowid() {
    return previousRowid;
  }

  public void setPreviousRowid(Integer previousRowid) {
    this.previousRowid = previousRowid;
  }

  public Row previousRowSequence(Integer previousRowSequence) {
    this.previousRowSequence = previousRowSequence;
    return this;
  }

  /**
   * Get previousRowSequence
   * @return previousRowSequence
   **/
  @JsonProperty("previousRowSequence")
  @ApiModelProperty(value = "")
  public Integer getPreviousRowSequence() {
    return previousRowSequence;
  }

  public void setPreviousRowSequence(Integer previousRowSequence) {
    this.previousRowSequence = previousRowSequence;
  }

  public Row active(Boolean active) {
    this.active = active;
    return this;
  }

  /**
   * Get active
   * @return active
   **/
  @JsonProperty("active")
  @ApiModelProperty(value = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public Row tid(Integer tid) {
    this.tid = tid;
    return this;
  }

  /**
   * Get tid
   * @return tid
   **/
  @JsonProperty("tid")
  @ApiModelProperty(value = "")
  public Integer getTid() {
    return tid;
  }

  public void setTid(Integer tid) {
    this.tid = tid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Row row = (Row) o;
    return Objects.equals(this.id, row.id) &&
        Objects.equals(this.seqNo, row.seqNo) &&
        Objects.equals(this.previousRowid, row.previousRowid) &&
        Objects.equals(this.previousRowSequence, row.previousRowSequence) &&
        Objects.equals(this.active, row.active) &&
        Objects.equals(this.tid, row.tid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, seqNo, previousRowid, previousRowSequence, active, tid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Row {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    seqNo: ").append(toIndentedString(seqNo)).append("\n");
    sb.append("    previousRowid: ").append(toIndentedString(previousRowid)).append("\n");
    sb.append("    previousRowSequence: ").append(toIndentedString(previousRowSequence)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    tid: ").append(toIndentedString(tid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

