/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;

/**
 * SequencedCellArray
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-05-07T10:23:52.356Z")
public class SequencedCellArray   {
  @JsonProperty("columnId")
  private Integer columnId = null;

  @JsonProperty("cellValues")
  private List<String> cellValues = null;

  public SequencedCellArray columnId(Integer columnId) {
    this.columnId = columnId;
    return this;
  }

  /**
   * Get columnId
   * @return columnId
   **/
  @JsonProperty("columnId")
  @ApiModelProperty(value = "")
  public Integer getColumnId() {
    return columnId;
  }

  public void setColumnId(Integer columnId) {
    this.columnId = columnId;
  }

  public SequencedCellArray cellValues(List<String> cellValues) {
    this.cellValues = cellValues;
    return this;
  }

  public SequencedCellArray addCellValuesItem(String cellValuesItem) {
    if (this.cellValues == null) {
      this.cellValues = new ArrayList<String>();
    }
    this.cellValues.add(cellValuesItem);
    return this;
  }

  /**
   * Get cellValues
   * @return cellValues
   **/
  @JsonProperty("cellValues")
  @ApiModelProperty(value = "")
  public List<String> getCellValues() {
    return cellValues;
  }

  public void setCellValues(List<String> cellValues) {
    this.cellValues = cellValues;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SequencedCellArray sequencedCellArray = (SequencedCellArray) o;
    return Objects.equals(this.columnId, sequencedCellArray.columnId) &&
        Objects.equals(this.cellValues, sequencedCellArray.cellValues);
  }

  @Override
  public int hashCode() {
    return Objects.hash(columnId, cellValues);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SequencedCellArray {\n");
    
    sb.append("    columnId: ").append(toIndentedString(columnId)).append("\n");
    sb.append("    cellValues: ").append(toIndentedString(cellValues)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

