/*
 * Boardwalk Collaboration Platform API
 * API for Boardwalk Collaboration Platform APIs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: rahul_var@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;

/**
 * ThisNhDetails
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-04-23T07:19:11.481Z")
public class ThisNhDetails   {
  @JsonProperty("this_level")
  private Integer thisLevel = null;

  @JsonProperty("level_0_id")
  private Integer level0Id = null;

  @JsonProperty("level_1_id")
  private Integer level1Id = null;

  @JsonProperty("level_2_id")
  private Integer level2Id = null;

  @JsonProperty("level_3_id")
  private Integer level3Id = null;

  @JsonProperty("is_secure")
  private Boolean isSecure = null;

  @JsonProperty("tx_id")
  private Integer txId = null;

  @JsonProperty("is_active")
  private Boolean isActive = null;

  @JsonProperty("created_by_id")
  private Integer createdById = null;

  @JsonProperty("created_on")
  private String createdOn = null;

  @JsonProperty("managed_by_id")
  private Integer managedById = null;

  @JsonProperty("nh_name")
  private String nhName = null;

  @JsonProperty("access")
  private Integer access = null;

  public ThisNhDetails thisLevel(Integer thisLevel) {
    this.thisLevel = thisLevel;
    return this;
  }

  /**
   * Get thisLevel
   * @return thisLevel
   **/
  @JsonProperty("this_level")
  @ApiModelProperty(example = "0 or 1 or 2 or 3", required = true, value = "")
  @NotNull
  public Integer getThisLevel() {
    return thisLevel;
  }

  public void setThisLevel(Integer thisLevel) {
    this.thisLevel = thisLevel;
  }

  public ThisNhDetails level0Id(Integer level0Id) {
    this.level0Id = level0Id;
    return this;
  }

  /**
   * Get level0Id
   * @return level0Id
   **/
  @JsonProperty("level_0_id")
  @ApiModelProperty(example = "12", required = true, value = "")
  @NotNull
  public Integer getLevel0Id() {
    return level0Id;
  }

  public void setLevel0Id(Integer level0Id) {
    this.level0Id = level0Id;
  }

  public ThisNhDetails level1Id(Integer level1Id) {
    this.level1Id = level1Id;
    return this;
  }

  /**
   * Get level1Id
   * @return level1Id
   **/
  @JsonProperty("level_1_id")
  @ApiModelProperty(example = "34", required = true, value = "")
  @NotNull
  public Integer getLevel1Id() {
    return level1Id;
  }

  public void setLevel1Id(Integer level1Id) {
    this.level1Id = level1Id;
  }

  public ThisNhDetails level2Id(Integer level2Id) {
    this.level2Id = level2Id;
    return this;
  }

  /**
   * Get level2Id
   * @return level2Id
   **/
  @JsonProperty("level_2_id")
  @ApiModelProperty(example = "124", required = true, value = "")
  @NotNull
  public Integer getLevel2Id() {
    return level2Id;
  }

  public void setLevel2Id(Integer level2Id) {
    this.level2Id = level2Id;
  }

  public ThisNhDetails level3Id(Integer level3Id) {
    this.level3Id = level3Id;
    return this;
  }

  /**
   * Get level3Id
   * @return level3Id
   **/
  @JsonProperty("level_3_id")
  @ApiModelProperty(example = "142", required = true, value = "")
  @NotNull
  public Integer getLevel3Id() {
    return level3Id;
  }

  public void setLevel3Id(Integer level3Id) {
    this.level3Id = level3Id;
  }

  public ThisNhDetails isSecure(Boolean isSecure) {
    this.isSecure = isSecure;
    return this;
  }

  /**
   * Get isSecure
   * @return isSecure
   **/
  @JsonProperty("is_secure")
  @ApiModelProperty(example = "false", required = true, value = "")
  @NotNull
  public Boolean isIsSecure() {
    return isSecure;
  }

  public void setIsSecure(Boolean isSecure) {
    this.isSecure = isSecure;
  }

  public ThisNhDetails txId(Integer txId) {
    this.txId = txId;
    return this;
  }

  /**
   * Get txId
   * @return txId
   **/
  @JsonProperty("tx_id")
  @ApiModelProperty(example = "3453", required = true, value = "")
  @NotNull
  public Integer getTxId() {
    return txId;
  }

  public void setTxId(Integer txId) {
    this.txId = txId;
  }

  public ThisNhDetails isActive(Boolean isActive) {
    this.isActive = isActive;
    return this;
  }

  /**
   * Get isActive
   * @return isActive
   **/
  @JsonProperty("is_active")
  @ApiModelProperty(example = "false", required = true, value = "")
  @NotNull
  public Boolean isIsActive() {
    return isActive;
  }

  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }

  public ThisNhDetails createdById(Integer createdById) {
    this.createdById = createdById;
    return this;
  }

  /**
   * Get createdById
   * @return createdById
   **/
  @JsonProperty("created_by_id")
  @ApiModelProperty(example = "32", required = true, value = "")
  @NotNull
  public Integer getCreatedById() {
    return createdById;
  }

  public void setCreatedById(Integer createdById) {
    this.createdById = createdById;
  }

  public ThisNhDetails createdOn(String createdOn) {
    this.createdOn = createdOn;
    return this;
  }

  /**
   * Get createdOn
   * @return createdOn
   **/
  @JsonProperty("created_on")
  @ApiModelProperty(example = "2016-08-29T09:12:33.001Z", required = true, value = "")
  @NotNull
  public String getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(String createdOn) {
    this.createdOn = createdOn;
  }

  public ThisNhDetails managedById(Integer managedById) {
    this.managedById = managedById;
    return this;
  }

  /**
   * Get managedById
   * @return managedById
   **/
  @JsonProperty("managed_by_id")
  @ApiModelProperty(example = "32", value = "")
  public Integer getManagedById() {
    return managedById;
  }

  public void setManagedById(Integer managedById) {
    this.managedById = managedById;
  }

  public ThisNhDetails nhName(String nhName) {
    this.nhName = nhName;
    return this;
  }

  /**
   * Get nhName
   * @return nhName
   **/
  @JsonProperty("nh_name")
  @ApiModelProperty(example = "APAC", required = true, value = "")
  @NotNull
  public String getNhName() {
    return nhName;
  }

  public void setNhName(String nhName) {
    this.nhName = nhName;
  }

  public ThisNhDetails access(Integer access) {
    this.access = access;
    return this;
  }

  /**
   * Get access
   * @return access
   **/
  @JsonProperty("access")
  @ApiModelProperty(example = "0 or 1", required = true, value = "")
  @NotNull
  public Integer getAccess() {
    return access;
  }

  public void setAccess(Integer access) {
    this.access = access;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ThisNhDetails thisNhDetails = (ThisNhDetails) o;
    return Objects.equals(this.thisLevel, thisNhDetails.thisLevel) &&
        Objects.equals(this.level0Id, thisNhDetails.level0Id) &&
        Objects.equals(this.level1Id, thisNhDetails.level1Id) &&
        Objects.equals(this.level2Id, thisNhDetails.level2Id) &&
        Objects.equals(this.level3Id, thisNhDetails.level3Id) &&
        Objects.equals(this.isSecure, thisNhDetails.isSecure) &&
        Objects.equals(this.txId, thisNhDetails.txId) &&
        Objects.equals(this.isActive, thisNhDetails.isActive) &&
        Objects.equals(this.createdById, thisNhDetails.createdById) &&
        Objects.equals(this.createdOn, thisNhDetails.createdOn) &&
        Objects.equals(this.managedById, thisNhDetails.managedById) &&
        Objects.equals(this.nhName, thisNhDetails.nhName) &&
        Objects.equals(this.access, thisNhDetails.access);
  }

  @Override
  public int hashCode() {
    return Objects.hash(thisLevel, level0Id, level1Id, level2Id, level3Id, isSecure, txId, isActive, createdById, createdOn, managedById, nhName, access);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ThisNhDetails {\n");
    
    sb.append("    thisLevel: ").append(toIndentedString(thisLevel)).append("\n");
    sb.append("    level0Id: ").append(toIndentedString(level0Id)).append("\n");
    sb.append("    level1Id: ").append(toIndentedString(level1Id)).append("\n");
    sb.append("    level2Id: ").append(toIndentedString(level2Id)).append("\n");
    sb.append("    level3Id: ").append(toIndentedString(level3Id)).append("\n");
    sb.append("    isSecure: ").append(toIndentedString(isSecure)).append("\n");
    sb.append("    txId: ").append(toIndentedString(txId)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    createdById: ").append(toIndentedString(createdById)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    managedById: ").append(toIndentedString(managedById)).append("\n");
    sb.append("    nhName: ").append(toIndentedString(nhName)).append("\n");
    sb.append("    access: ").append(toIndentedString(access)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

