/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;

/**
 * Grid
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-05-10T14:51:11.960Z")
public class Grid   {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("collabId")
  private Integer collabId = null;

  @JsonProperty("wbId")
  private Integer wbId = null;

  @JsonProperty("memberId")
  private Integer memberId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  public Grid id(Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   **/
  @JsonProperty("id")
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Grid collabId(Integer collabId) {
    this.collabId = collabId;
    return this;
  }

  /**
   * Get collabId
   * @return collabId
   **/
  @JsonProperty("collabId")
  @ApiModelProperty(value = "")
  public Integer getCollabId() {
    return collabId;
  }

  public void setCollabId(Integer collabId) {
    this.collabId = collabId;
  }

  public Grid wbId(Integer wbId) {
    this.wbId = wbId;
    return this;
  }

  /**
   * Get wbId
   * @return wbId
   **/
  @JsonProperty("wbId")
  @ApiModelProperty(value = "")
  public Integer getWbId() {
    return wbId;
  }

  public void setWbId(Integer wbId) {
    this.wbId = wbId;
  }

  public Grid memberId(Integer memberId) {
    this.memberId = memberId;
    return this;
  }

  /**
   * Get memberId
   * @return memberId
   **/
  @JsonProperty("memberId")
  @ApiModelProperty(value = "")
  public Integer getMemberId() {
    return memberId;
  }

  public void setMemberId(Integer memberId) {
    this.memberId = memberId;
  }

  public Grid name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   **/
  @JsonProperty("name")
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Grid description(String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   **/
  @JsonProperty("description")
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Grid grid = (Grid) o;
    return Objects.equals(this.id, grid.id) &&
        Objects.equals(this.collabId, grid.collabId) &&
        Objects.equals(this.wbId, grid.wbId) &&
        Objects.equals(this.memberId, grid.memberId) &&
        Objects.equals(this.name, grid.name) &&
        Objects.equals(this.description, grid.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, collabId, wbId, memberId, name, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Grid {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    collabId: ").append(toIndentedString(collabId)).append("\n");
    sb.append("    wbId: ").append(toIndentedString(wbId)).append("\n");
    sb.append("    memberId: ").append(toIndentedString(memberId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

